services:
  graph-node-zoo:
    container_name: graph-node-zoo
    image: ghcr.io/luxfi/graph-node:latest
    ports:
      - '8100:8000'  # GraphQL Query endpoint
      - '8101:8001'  # GraphQL Subscription endpoint
      - '8120:8020'  # Admin endpoint
      - '8140:8040'  # Prometheus metrics endpoint
    extra_hosts:
      - zoonet:192.168.1.165
      - host.docker.internal:host-gateway
    environment:
      postgres_host: zoonet
      postgres_user: lux
      postgres_pass: oi1dAc9bad8MSc2da51a2544f0cb8e16lb21A
      postgres_db: graph_zoonet
      ipfs: 'zoonet:5555'
      ethereum: 'zoo:http://zoonet:8080'
      GRAPH_LOG: debug
      RUST_BACKTRACE: 1
